### ISSUE TITLE
请问部署到腾讯云函数，执行方法是啥

### ISSUE THREAD

**Issue by YYplus** [hwkxk/HeytapTask#10]
一直找不到函数执行入口文件

**Comment by PDxtXHd** [comment]
自己动手丰衣足食

**Comment by hwkxk** [comment]
> 一直找不到函数执行入口文件

建议查看这个腾讯云函数文档：https://cloud.tencent.com/document/product/583/19805
执行方法的格式里面写的很清楚：文件名.函数入口 ，
本项目的文件名就是：main.main 自己改一下不就好了。
还要把2个py文件的./log.txt 改成 ../../tmp/log.txt 就没问题了。
