### ISSUE TITLE
云函数测试出错

### ISSUE THREAD

**Issue by fghjkln22222** [hwkxk/HeytapTask#11]
返回结果：{"errorCode":-1,"errorMessage":"Invoking task timed out after 20 seconds","requestId":"dfffc64b-83d3-42cd-9eae-65c7c2e80565","statusCode":433}
日志：==== 欢太商城任务 ====

[2021-07-26 06:11:42,932]:INFO:==== 欢太商城任务 ====

【登录成功】: 用户01456796

[2021-07-26 06:11:42,932]:INFO:【登录成功】: 用户01456796

【每日签到】: 已经签到过了！

[2021-07-26 06:11:43,213]:INFO:【每日签到】: 已经签到过了！

正在浏览商品ID： 1955

正在浏览商品ID： 4075

正在浏览商品ID： 4874

**Comment by hwkxk** [comment]
#### 请不要在这咨询项目代码之外的问题了，Invoking task timed out after 20 seconds 不会翻译一下？云函数设置执行超时时间只有20秒。重新设置一下
