### ISSUE TITLE
抽奖和昨天加的任务咋都删啦？

### ISSUE THREAD

**Issue by lpxtennan** [hwkxk/HeytapTask#2]
啥情况呀？这些任务有风险吗？

**Comment by hwkxk** [comment]
#### 可能会黑号，今天所有转盘都没中，暂时撤回了~

**Comment by lpxtennan** [comment]
> #### 可能会黑号，今天所有转盘都没中，暂时撤回了~

大佬能否看下昨天加的狂撒百万积分任务，去掉转盘抽奖那部分，剩下的签到浏览任务是否安全可用？这部分能给25积分呢

**Comment by bugme2** [comment]
> #### 可能会黑号，今天所有转盘都没中，暂时撤回了~

中奖概率变低了，我之前手动做一样不中，不关脚本的事
