### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by spiritLHL** [hwkxk/HeytapTask#21]
![4NRDXBVZ~_NL_K4UWILZV_T.png](https://i.loli.net/2021/08/04/kPU4DGvX7zJSITi.png)
可以签到，但是迭代错误，应该是哪里有问题了，试过各种环境执行，不是ck问题

**Comment by spiritLHL** [comment]
> 
> #### 在res = taskCenter() 的下方插入 一行 print (res)，运行一下，贴一下打印出来的任务json数据

{'code': 200, 'data': {'userCredits': 5, 'noviceList': None, 'everydayList': None, 'buyList': None, 'startTime': None, 'endTime': None, 'currentTime': 1628080531647, 'waterStartTime': 1564122600000, 'waterEndTime': 1565971199000, 'isStart': 0, 'userReportInfoForm': {'reportDays': 1, 'status': 1, 'gifts': [{'date': '2021-08-04', 'gift': '', 'credits': 5, 'today': True, 'id': 1, 'type': ''}, {'date': '2021-08-05', 'gift': '', 'credits': 5, 'today': False, 'id': 2, 'type': ''}, {'date': '2021-08-06', 'gift': '', 'credits': 7, 'today': False, 'id': 3, 'type': ''}, {'date': '2021-08-07', 'gift': '', 'credits': 7, 'today': False, 'id': 4, 'type': ''}, {'date': '2021-08-08', 'gift': '', 'credits': 9, 'today': False, 'id': 5, 'type': ''}, {'date': '2021-08-09', 'gift': '', 'credits': 9, 'today': False, 'id': 6, 'type': ''}, {'date': '2021-08-10', 'gift': '', 'credits': 10, 'today': False, 'id': 7, 'type': ''}]}}}

**Comment by hwkxk** [comment]
####  UA换成自己了没？你这个返回任务列表没有数据，只有签到的。进APP看看是否正常吧，暂时我这边没有遇到。

**Comment by spiritLHL** [comment]
> 
> #### UA换成自己了没？你这个返回任务列表没有数据，只有签到的。进APP看看是否正常吧，暂时我这边没有遇到。

好吧，我换了自己手机的UA，还是一样报错，不知道咋回事，将就用了

**Comment by hwkxk** [comment]
> > #### UA换成自己了没？你这个返回任务列表没有数据，只有签到的。进APP看看是否正常吧，暂时我这边没有遇到。
> 
> 好吧，我换了自己手机的UA，还是一样报错，不知道咋回事，将就用了

#17 这里已经有人排查出来解决了

**Comment by spiritLHL** [comment]
> 
> 
> > > #### UA换成自己了没？你这个返回任务列表没有数据，只有签到的。进APP看看是否正常吧，暂时我这边没有遇到。
> > 
> > 
> > 好吧，我换了自己手机的UA，还是一样报错，不知道咋回事，将就用了
> 
> [#17 ](https://github.com/hwkxk/HeytapTask/issues/17) 这里已经有人排查出来解决了

我明白哪里问题了，是得自己先进入一次任务中心，然后才能获取到数据，新号之前没进过任务中心会无法获取到数据
