### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xm1898** [hwkxk/HeytapTask#26]
【每日签到】: 已经签到过了！

【每日浏览任务】: 错误，原因为: 'NoneType' object is not iterable

【每日分享商品】: 错误，原因为: 'NoneType' object is not iterable

【每日推送消息】: 错误，原因为: 'NoneType' object is not iterable
这样是什么原因呢？

**Comment by poorld** [comment]
一样

**Comment by hwkxk** [comment]
使用注意没看到吗？认真看一遍！
