### ISSUE TITLE
大佬，你提供的方法都试遍了，还是不行，求帮忙看下

### ISSUE THREAD

**Issue by providencor** [hwkxk/HeytapTask#37]
START RequestId:7326b802-f981-4734-b4e5-c619e435c199
ERROR RequestId:7326b802-f981-4734-b4e5-c619e435c199 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 160, in get_func_handler\n    return getattr(mod, fname)\nAttributeError: module 'main' has no attribute 'main_handler'","statusCode":443}
END RequestId:7326b802-f981-4734-b4e5-c619e435c199
Report RequestId:7326b802-f981-4734-b4e5-c619e435c199 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by hwkxk** [comment]
#### 就是你了  请把你copy的旧仓源码删掉 或者 转私密谢谢！不要再公开我的旧源，你这个`AttributeError: module 'main' has no attribute 'main_handler' `

**Comment by providencor** [comment]
抱歉，旧源我也是别人那里看到的，马上删了，万分抱歉抱歉，刚刚自己搜索测试已经解决，看不懂代码..
