### ISSUE TITLE
UnboundLocalError: local variable 'qd' referenced before assignment 点推送消息-任务没了

### ISSUE THREAD

**Issue by rubnet** [hwkxk/HeytapTask#46]
Traceback (most recent call last):
  File "HeytapTask.py", line xxx, in daily_viewpush
    if qd['completeStatus'] == 0:
UnboundLocalError: local variable 'qd' referenced before assignment

**Comment by hwkxk** [comment]
没了就注释` #daily_sharegoods() `

**Comment by rubnet** [comment]
好的`                  #  self.daily_viewpush()  # 执行每日点推送任务
`
